version: '3'
services:
  app:
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./:/app

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ".docker/.env"